spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=JST
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: none